// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const dimensions = {
  beatgrid: "26px",
  sizeMedium: "16px",
  sizeSmall: "8px",
  sizeXlarge: "40px",
  xlarge: "100px",
};
export const radius = {
  radiusLarge: "16px",
  radiusMedium: "8px",
  radiusPill: "9999999px",
  radiusSmall: "4px",
};
export const spacing = {
  paddingLarge: "16px",
  paddingMedium: "8px",
  paddingSmall: "4px",
  spaceMedium: "8px",
  spaceSmall: "4px",
  spacingLarge: "16px",
};
