// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../../textstyles/fonts.css";
import "../../reset.css";
import "./Logo.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../../_internal_utils";
import { RootPrimitive, ImagePrimitive } from "../../_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const LogoContext = createContext(null);

function Logo(_props) {
  const defaults = useContext(LogoContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="TA7LAk3fe6"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "TA7LAk3fe6",
        scope: "LqFKBnUPnP",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <ImagePrimitive
          id={"Image_FJo7FTEKuo"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_LqFKBnUPnP_FJo7FTEKuo"
          }
          key={"FJo7FTEKuo"}
          src={
            exists(props.imageSrc)
              ? props.imageSrc
              : getStyle("FJo7FTEKuo", "src")
          }
          alt={getStyle("FJo7FTEKuo", "alternateText")}
        />
      )}
    </RootPrimitive>
  );
}

Logo.__variants = [];

export default Logo;
