// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../../textstyles/fonts.css";
import "../../reset.css";
import "./SignIn.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../../_internal_utils";
import { RootPrimitive } from "../../_internal_primitives";
import * as icons from "../../icons";
import { default as Button, ButtonContext } from "../../Button";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      "3nbXUv6VoL": {
        none: {
          text: "SignIn",
          icon: icons.externalLink,
          kind: "secondary",
          withIcon: true,
        },
      },
    },
  },
];

const variantPropTypes = [];

export const SignInContext = createContext(null);

function SignIn(_props) {
  const defaults = useContext(SignInContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="3cUuDHpigw"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "3cUuDHpigw",
        scope: "2Sc6yyoKXd",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) =>
        props.Button === undefined ? (
          <Button
            key={"3nbXUv6VoL"}
            {...getCompositeDefaultProps("3nbXUv6VoL")}
            id="Button_3nbXUv6VoL"
            className="__visly_reset_7X7HTLRqyD __visly_scope_2Sc6yyoKXd_3nbXUv6VoL"
          />
        ) : (
          <ButtonContext.Provider
            key="3nbXUv6VoL-provider"
            value={{
              key: "3nbXUv6VoL",
              id: "Button_3nbXUv6VoL",
              className:
                "__visly_reset_7X7HTLRqyD __visly_scope_2Sc6yyoKXd_3nbXUv6VoL",
              ...getCompositeDefaultProps("3nbXUv6VoL"),
            }}
          >
            {props.Button}
          </ButtonContext.Provider>
        )
      }
    </RootPrimitive>
  );
}

SignIn.Button = Button;
SignIn.__variants = [];

export default SignIn;
