// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../../textstyles/fonts.css";
import "../../reset.css";
import "./Settings.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../../_internal_utils";
import {
  RootPrimitive,
  TextPrimitive,
  ContainerPrimitive,
} from "../../_internal_primitives";
import { default as Button, ButtonContext } from "../../Button";
import {
  default as Name,
  InputContext as NameContext,
  default as Bio,
  InputContext as BioContext,
} from "../../Input";

const styles = [
  {
    type: "default",
    layers: {
      C7kKiYWNYR: {
        none: {
          text: "Name:",
        },
      },
      "6L724DTTs4": {
        none: {
          text: "Bio:",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      ARV5v7xQn1: {
        none: {
          text: "Update",
        },
      },
      X9hbsyPzjn: {
        none: {
          placeholder: "Jane Doe",
        },
      },
      "47yRWFbghA": {
        none: {
          placeholder: "Jane Doe",
        },
      },
    },
  },
];

const variantPropTypes = [];

export const SettingsContext = createContext(null);

function Settings(_props) {
  const defaults = useContext(SettingsContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="SnqYQ3m7Vh"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "SnqYQ3m7Vh",
        scope: "Hez1oCiZ3N",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <ContainerPrimitive
            id={"Container_6dfTcgCw5P"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_Hez1oCiZ3N_6dfTcgCw5P"
            }
            key={"6dfTcgCw5P"}
            addSpacing={false}
            element={getStyle("6dfTcgCw5P", "htmlElement")}
          >
            <ContainerPrimitive
              id={"Container_R8RdFbdKkf"}
              className={
                "__visly_reset_7X7HTLRqyD __visly_scope_Hez1oCiZ3N_R8RdFbdKkf"
              }
              key={"R8RdFbdKkf"}
              addSpacing={false}
              element={getStyle("R8RdFbdKkf", "htmlElement")}
            >
              <TextPrimitive
                id={"Name_C7kKiYWNYR"}
                className={
                  "__visly_reset_7X7HTLRqyD __visly_scope_Hez1oCiZ3N_C7kKiYWNYR"
                }
                key={"C7kKiYWNYR"}
                text={getStyle("C7kKiYWNYR", "text")}
                element={getStyle("C7kKiYWNYR", "htmlElement")}
              />
              <TextPrimitive
                id={"Bio_6L724DTTs4"}
                className={
                  "__visly_reset_7X7HTLRqyD __visly_scope_Hez1oCiZ3N_6L724DTTs4"
                }
                key={"6L724DTTs4"}
                text={getStyle("6L724DTTs4", "text")}
                element={getStyle("6L724DTTs4", "htmlElement")}
              />
            </ContainerPrimitive>
            <ContainerPrimitive
              id={"Container_UjGoXgs92e"}
              className={
                "__visly_reset_7X7HTLRqyD __visly_scope_Hez1oCiZ3N_UjGoXgs92e"
              }
              key={"UjGoXgs92e"}
              addSpacing={true}
              element={getStyle("UjGoXgs92e", "htmlElement")}
            >
              {[
                props.Name === undefined ? (
                  <Name
                    key={"X9hbsyPzjn"}
                    {...getCompositeDefaultProps("X9hbsyPzjn")}
                    id="Name_X9hbsyPzjn"
                    className="__visly_reset_7X7HTLRqyD __visly_scope_Hez1oCiZ3N_X9hbsyPzjn"
                  />
                ) : (
                  <NameContext.Provider
                    key="X9hbsyPzjn-provider"
                    value={{
                      key: "X9hbsyPzjn",
                      id: "Name_X9hbsyPzjn",
                      className:
                        "__visly_reset_7X7HTLRqyD __visly_scope_Hez1oCiZ3N_X9hbsyPzjn",
                      ...getCompositeDefaultProps("X9hbsyPzjn"),
                    }}
                  >
                    {props.Name}
                  </NameContext.Provider>
                ),
                props.Bio === undefined ? (
                  <Bio
                    key={"47yRWFbghA"}
                    {...getCompositeDefaultProps("47yRWFbghA")}
                    id="Bio_47yRWFbghA"
                    className="__visly_reset_7X7HTLRqyD __visly_scope_Hez1oCiZ3N_47yRWFbghA"
                  />
                ) : (
                  <BioContext.Provider
                    key="47yRWFbghA-provider"
                    value={{
                      key: "47yRWFbghA",
                      id: "Bio_47yRWFbghA",
                      className:
                        "__visly_reset_7X7HTLRqyD __visly_scope_Hez1oCiZ3N_47yRWFbghA",
                      ...getCompositeDefaultProps("47yRWFbghA"),
                    }}
                  >
                    {props.Bio}
                  </BioContext.Provider>
                ),
              ]}
            </ContainerPrimitive>
          </ContainerPrimitive>
          <ContainerPrimitive
            id={"Container_2SrtPbtkds"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_Hez1oCiZ3N_2SrtPbtkds"
            }
            key={"2SrtPbtkds"}
            addSpacing={false}
            element={getStyle("2SrtPbtkds", "htmlElement")}
          >
            {props.Button === undefined ? (
              <Button
                key={"ARV5v7xQn1"}
                {...getCompositeDefaultProps("ARV5v7xQn1")}
                id="Button_ARV5v7xQn1"
                className="__visly_reset_7X7HTLRqyD __visly_scope_Hez1oCiZ3N_ARV5v7xQn1"
              />
            ) : (
              <ButtonContext.Provider
                key="ARV5v7xQn1-provider"
                value={{
                  key: "ARV5v7xQn1",
                  id: "Button_ARV5v7xQn1",
                  className:
                    "__visly_reset_7X7HTLRqyD __visly_scope_Hez1oCiZ3N_ARV5v7xQn1",
                  ...getCompositeDefaultProps("ARV5v7xQn1"),
                }}
              >
                {props.Button}
              </ButtonContext.Provider>
            )}
          </ContainerPrimitive>
        </>
      )}
    </RootPrimitive>
  );
}

Settings.Button = Button;
Settings.Name = Name;
Settings.Bio = Bio;
Settings.__variants = [];

export default Settings;
