// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../../../textstyles/fonts.css";
import "../../../reset.css";
import "./ControlButton.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../../../_internal_utils";
import { RootPrimitive, IconPrimitive } from "../../../_internal_primitives";
import * as icons from "../../../icons";

const styles = [
  {
    type: "default",
    layers: {
      W4r7yiSBXP: {
        none: {
          icon: icons.vislyRadioCenter,
          useMask: true,
        },
        pressed: {
          useMask: true,
        },
        disabled: {
          useMask: true,
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const ControlButtonContext = createContext(null);

function ControlButton(_props) {
  const defaults = useContext(ControlButtonContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="D9RTWhw5ad"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "D9RTWhw5ad",
        scope: "Lj97Tq5SuJ",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <IconPrimitive
          id={"Icon_W4r7yiSBXP"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_Lj97Tq5SuJ_W4r7yiSBXP"
          }
          key={"W4r7yiSBXP"}
          useMask={getStyle("W4r7yiSBXP", "useMask")}
          src={getStyle("W4r7yiSBXP", "icon")}
        />
      )}
    </RootPrimitive>
  );
}

ControlButton.__variants = [];

export default ControlButton;
