// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import component_0 from "./ControlButton";
import component_1 from "./SongControl";
import component_2 from "./SongControl.Bpm";
import component_3 from "./SongInfo";
import component_4 from "./SongInfo.ExampleTracks";
export const ControlButton = component_0;
export const SongControl = component_1;
export const SongInfo = component_3;
SongControl.Bpm = component_2;
SongInfo.ExampleTracks = component_4;
