// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../../../textstyles/fonts.css";
import "../../../reset.css";
import "./SongInfo.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../../../_internal_utils";
import {
  RootPrimitive,
  TextPrimitive,
  ContainerPrimitive,
} from "../../../_internal_primitives";
import {
  default as SongControl,
  SongControlContext,
} from "../../../Components/Editor/Song/SongControl";

const styles = [
  {
    type: "default",
    layers: {
      "76aFBWckZf": {
        none: {
          text: "Song Name",
        },
      },
      U4FCXZYr8Y: {
        none: {
          text: "Your Focus:",
        },
      },
      CJnPE7hAa5: {
        none: {
          text: "Effects",
        },
      },
      Ps7RDgwaoV: {
        none: {
          text: "Completed:",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      VYZ6MR15rv: {},
    },
  },
];

const variantPropTypes = [];

export const SongInfoContext = createContext(null);

function SongInfo(_props) {
  const defaults = useContext(SongInfoContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="L1X4991qBT"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "L1X4991qBT",
        scope: "8kA8YvNeKj",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <ContainerPrimitive
            id={"Container_LY6s5iGzno"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_8kA8YvNeKj_LY6s5iGzno"
            }
            key={"LY6s5iGzno"}
            addSpacing={false}
            element={getStyle("LY6s5iGzno", "htmlElement")}
          >
            {[
              <ContainerPrimitive
                id={"Container_6Dn9vbmn96"}
                className={
                  "__visly_reset_7X7HTLRqyD __visly_scope_8kA8YvNeKj_6Dn9vbmn96"
                }
                key={"6Dn9vbmn96"}
                addSpacing={false}
                element={getStyle("6Dn9vbmn96", "htmlElement")}
              >
                <TextPrimitive
                  id={"Name_76aFBWckZf"}
                  className={
                    "__visly_reset_7X7HTLRqyD __visly_scope_8kA8YvNeKj_76aFBWckZf"
                  }
                  key={"76aFBWckZf"}
                  text={
                    exists(props.text)
                      ? props.text
                      : getStyle("76aFBWckZf", "text")
                  }
                  element={getStyle("76aFBWckZf", "htmlElement")}
                />
                <ContainerPrimitive
                  id={"Container_Wrd2Kfd8Z7"}
                  className={
                    "__visly_reset_7X7HTLRqyD __visly_scope_8kA8YvNeKj_Wrd2Kfd8Z7"
                  }
                  key={"Wrd2Kfd8Z7"}
                  addSpacing={false}
                  element={getStyle("Wrd2Kfd8Z7", "htmlElement")}
                >
                  <TextPrimitive
                    id={"Your Focus_U4FCXZYr8Y"}
                    className={
                      "__visly_reset_7X7HTLRqyD __visly_scope_8kA8YvNeKj_U4FCXZYr8Y"
                    }
                    key={"U4FCXZYr8Y"}
                    text={getStyle("U4FCXZYr8Y", "text")}
                    element={getStyle("U4FCXZYr8Y", "htmlElement")}
                  />
                  <TextPrimitive
                    id={"Track Type_CJnPE7hAa5"}
                    className={
                      "__visly_reset_7X7HTLRqyD __visly_scope_8kA8YvNeKj_CJnPE7hAa5"
                    }
                    key={"CJnPE7hAa5"}
                    text={
                      exists(props.trackFocus)
                        ? props.trackFocus
                        : getStyle("CJnPE7hAa5", "text")
                    }
                    element={getStyle("CJnPE7hAa5", "htmlElement")}
                  />
                </ContainerPrimitive>
              </ContainerPrimitive>,
              props.SongControl === undefined ? (
                <SongControl
                  key={"VYZ6MR15rv"}
                  {...getCompositeDefaultProps("VYZ6MR15rv")}
                  id="SongControl_VYZ6MR15rv"
                  className="__visly_reset_7X7HTLRqyD __visly_scope_8kA8YvNeKj_VYZ6MR15rv"
                />
              ) : (
                <SongControlContext.Provider
                  key="VYZ6MR15rv-provider"
                  value={{
                    key: "VYZ6MR15rv",
                    id: "SongControl_VYZ6MR15rv",
                    className:
                      "__visly_reset_7X7HTLRqyD __visly_scope_8kA8YvNeKj_VYZ6MR15rv",
                    ...getCompositeDefaultProps("VYZ6MR15rv"),
                  }}
                >
                  {props.SongControl}
                </SongControlContext.Provider>
              ),
            ]}
          </ContainerPrimitive>
          <ContainerPrimitive
            id={"Container_7SxCbTHQn2"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_8kA8YvNeKj_7SxCbTHQn2"
            }
            key={"7SxCbTHQn2"}
            addSpacing={false}
            element={getStyle("7SxCbTHQn2", "htmlElement")}
          >
            <TextPrimitive
              id={"Text_Ps7RDgwaoV"}
              className={
                "__visly_reset_7X7HTLRqyD __visly_scope_8kA8YvNeKj_Ps7RDgwaoV"
              }
              key={"Ps7RDgwaoV"}
              text={getStyle("Ps7RDgwaoV", "text")}
              element={getStyle("Ps7RDgwaoV", "htmlElement")}
            />
            <ContainerPrimitive
              key={"Wn2pFanHXX"}
              id={"Slot_Wn2pFanHXX"}
              className={
                "__visly_reset_7X7HTLRqyD __visly_scope_8kA8YvNeKj_Wn2pFanHXX"
              }
              addSpacing={false}
            >
              {props.ExistingTracks}
            </ContainerPrimitive>
          </ContainerPrimitive>
        </>
      )}
    </RootPrimitive>
  );
}

SongInfo.SongControl = SongControl;
SongInfo.__variants = [];

export default SongInfo;
