// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../../../textstyles/fonts.css";
import "../../../reset.css";
import "./SongControl.Bpm.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../../../_internal_utils";
import { RootPrimitive, TextPrimitive } from "../../../_internal_primitives";
import * as icons from "../../../icons";
import {
  default as ControlButton,
  ControlButtonContext,
  default as ControlButton1,
  ControlButtonContext as ControlButton1Context,
} from "../../../Components/Editor/Song/ControlButton";

const styles = [
  {
    type: "default",
    layers: {
      U2xbjPKvTG: {
        none: {
          text: "198 bpm",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      "8cf8ykYYY2": {
        none: {
          icon: icons.minus,
        },
      },
      Lc1Y7VXszo: {
        none: {
          icon: icons.plus,
        },
      },
    },
  },
];

const variantPropTypes = [];

export const BpmContext = createContext(null);

function Bpm(_props) {
  const defaults = useContext(BpmContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="FDzTFQPDng"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "FDzTFQPDng",
        scope: "RMoSfFZHdm",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => [
        props.ControlButton === undefined ? (
          <ControlButton
            key={"8cf8ykYYY2"}
            {...getCompositeDefaultProps("8cf8ykYYY2")}
            id="ControlButton_8cf8ykYYY2"
            className="__visly_reset_7X7HTLRqyD __visly_scope_RMoSfFZHdm_8cf8ykYYY2"
          />
        ) : (
          <ControlButtonContext.Provider
            key="8cf8ykYYY2-provider"
            value={{
              key: "8cf8ykYYY2",
              id: "ControlButton_8cf8ykYYY2",
              className:
                "__visly_reset_7X7HTLRqyD __visly_scope_RMoSfFZHdm_8cf8ykYYY2",
              ...getCompositeDefaultProps("8cf8ykYYY2"),
            }}
          >
            {props.ControlButton}
          </ControlButtonContext.Provider>
        ),
        <TextPrimitive
          id={"Text_U2xbjPKvTG"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_RMoSfFZHdm_U2xbjPKvTG"
          }
          key={"U2xbjPKvTG"}
          text={getStyle("U2xbjPKvTG", "text")}
          element={getStyle("U2xbjPKvTG", "htmlElement")}
        />,
        props.ControlButton1 === undefined ? (
          <ControlButton1
            key={"Lc1Y7VXszo"}
            {...getCompositeDefaultProps("Lc1Y7VXszo")}
            id="ControlButton1_Lc1Y7VXszo"
            className="__visly_reset_7X7HTLRqyD __visly_scope_RMoSfFZHdm_Lc1Y7VXszo"
          />
        ) : (
          <ControlButton1Context.Provider
            key="Lc1Y7VXszo-provider"
            value={{
              key: "Lc1Y7VXszo",
              id: "ControlButton1_Lc1Y7VXszo",
              className:
                "__visly_reset_7X7HTLRqyD __visly_scope_RMoSfFZHdm_Lc1Y7VXszo",
              ...getCompositeDefaultProps("Lc1Y7VXszo"),
            }}
          >
            {props.ControlButton1}
          </ControlButton1Context.Provider>
        ),
      ]}
    </RootPrimitive>
  );
}

Bpm.ControlButton = ControlButton;
Bpm.ControlButton1 = ControlButton1;
Bpm.__variants = [];

export default Bpm;
