// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../../textstyles/fonts.css";
import "../../reset.css";
import "./Daw.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../../_internal_utils";
import { RootPrimitive, ContainerPrimitive } from "../../_internal_primitives";
import * as icons from "../../icons";
import {
  default as TrackTable,
  TrackTableContext,
} from "../../Components/Editor/Track/TrackTable";
import {
  default as SongInfo,
  SongInfoContext,
} from "../../Components/Editor/Song/SongInfo";
import {
  default as SubmitButton,
  ButtonContext as SubmitButtonContext,
} from "../../Button";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      "8DLWbwv9QP": {},
      LuHHHachra: {},
      Uyf5C5sbD5: {
        none: {
          text: "Submit",
          icon: icons.edit,
          kind: "primary",
          withIcon: true,
        },
      },
    },
  },
];

const variantPropTypes = [];

export const DawContext = createContext(null);

function Daw(_props) {
  const defaults = useContext(DawContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="M1nWXX4cTf"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "M1nWXX4cTf",
        scope: "SpTbokBXfn",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => [
        props.SongInfo === undefined ? (
          <SongInfo
            key={"LuHHHachra"}
            {...getCompositeDefaultProps("LuHHHachra")}
            id="SongInfo_LuHHHachra"
            className="__visly_reset_7X7HTLRqyD __visly_scope_SpTbokBXfn_LuHHHachra"
          />
        ) : (
          <SongInfoContext.Provider
            key="LuHHHachra-provider"
            value={{
              key: "LuHHHachra",
              id: "SongInfo_LuHHHachra",
              className:
                "__visly_reset_7X7HTLRqyD __visly_scope_SpTbokBXfn_LuHHHachra",
              ...getCompositeDefaultProps("LuHHHachra"),
            }}
          >
            {props.SongInfo}
          </SongInfoContext.Provider>
        ),
        props.TrackTable === undefined ? (
          <TrackTable
            key={"8DLWbwv9QP"}
            {...getCompositeDefaultProps("8DLWbwv9QP")}
            id="TrackTable_8DLWbwv9QP"
            className="__visly_reset_7X7HTLRqyD __visly_scope_SpTbokBXfn_8DLWbwv9QP"
          />
        ) : (
          <TrackTableContext.Provider
            key="8DLWbwv9QP-provider"
            value={{
              key: "8DLWbwv9QP",
              id: "TrackTable_8DLWbwv9QP",
              className:
                "__visly_reset_7X7HTLRqyD __visly_scope_SpTbokBXfn_8DLWbwv9QP",
              ...getCompositeDefaultProps("8DLWbwv9QP"),
            }}
          >
            {props.TrackTable}
          </TrackTableContext.Provider>
        ),
        <ContainerPrimitive
          id={"Container_RQw9aRs1Aw"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_SpTbokBXfn_RQw9aRs1Aw"
          }
          key={"RQw9aRs1Aw"}
          addSpacing={false}
          element={getStyle("RQw9aRs1Aw", "htmlElement")}
        >
          {props.SubmitButton === undefined ? (
            <SubmitButton
              key={"Uyf5C5sbD5"}
              {...getCompositeDefaultProps("Uyf5C5sbD5")}
              id="SubmitButton_Uyf5C5sbD5"
              className="__visly_reset_7X7HTLRqyD __visly_scope_SpTbokBXfn_Uyf5C5sbD5"
            />
          ) : (
            <SubmitButtonContext.Provider
              key="Uyf5C5sbD5-provider"
              value={{
                key: "Uyf5C5sbD5",
                id: "SubmitButton_Uyf5C5sbD5",
                className:
                  "__visly_reset_7X7HTLRqyD __visly_scope_SpTbokBXfn_Uyf5C5sbD5",
                ...getCompositeDefaultProps("Uyf5C5sbD5"),
              }}
            >
              {props.SubmitButton}
            </SubmitButtonContext.Provider>
          )}
        </ContainerPrimitive>,
      ]}
    </RootPrimitive>
  );
}

Daw.TrackTable = TrackTable;
Daw.SongInfo = SongInfo;
Daw.SubmitButton = SubmitButton;
Daw.__variants = [];

export default Daw;
