// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../../textstyles/fonts.css";
import "../../reset.css";
import "./LabelledInput.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../../_internal_utils";
import { RootPrimitive, TextPrimitive } from "../../_internal_primitives";
import { default as Input, InputContext } from "../../Input";

const styles = [
  {
    type: "default",
    layers: {
      DhkLcS5J2U: {
        none: {
          text: "Label: ",
          htmlElement: "h3",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      BJSKncy5QG: {},
    },
  },
];

const variantPropTypes = [];

export const LabelledInputContext = createContext(null);

function LabelledInput(_props) {
  const defaults = useContext(LabelledInputContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="XuS6PWrrR8"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "XuS6PWrrR8",
        scope: "Hdwq9RMjqz",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => [
        <TextPrimitive
          id={"Text_DhkLcS5J2U"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_Hdwq9RMjqz_DhkLcS5J2U"
          }
          key={"DhkLcS5J2U"}
          text={
            exists(props.text) ? props.text : getStyle("DhkLcS5J2U", "text")
          }
          element={getStyle("DhkLcS5J2U", "htmlElement")}
        />,
        props.Input === undefined ? (
          <Input
            key={"BJSKncy5QG"}
            {...getCompositeDefaultProps("BJSKncy5QG")}
            id="Input_BJSKncy5QG"
            className="__visly_reset_7X7HTLRqyD __visly_scope_Hdwq9RMjqz_BJSKncy5QG"
          />
        ) : (
          <InputContext.Provider
            key="BJSKncy5QG-provider"
            value={{
              key: "BJSKncy5QG",
              id: "Input_BJSKncy5QG",
              className:
                "__visly_reset_7X7HTLRqyD __visly_scope_Hdwq9RMjqz_BJSKncy5QG",
              ...getCompositeDefaultProps("BJSKncy5QG"),
            }}
          >
            {props.Input}
          </InputContext.Provider>
        ),
      ]}
    </RootPrimitive>
  );
}

LabelledInput.Input = Input;
LabelledInput.__variants = [];

export default LabelledInput;
