// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import component_0 from "./Landing";
import component_1 from "./Navbar";
export const Landing = component_0;
export const Navbar = component_1;
