// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "../reset.css";
import "./Landing.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../_internal_utils";
import {
  RootPrimitive,
  ImagePrimitive,
  TextPrimitive,
  ContainerPrimitive,
} from "../_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {
      Rhtn315AoC: {
        none: {
          text: "Beat School",
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "example",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "example",
    layers: {},
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "example",
  },
];

export const LandingContext = createContext(null);

function Landing(_props) {
  const defaults = useContext(LandingContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="KkFEYX3E9N"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "KkFEYX3E9N",
        scope: "66HuVt3A5E",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <ContainerPrimitive
            id={"Container_D7HJQkH2Bb"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_66HuVt3A5E_D7HJQkH2Bb"
            }
            key={"D7HJQkH2Bb"}
            addSpacing={false}
            element={getStyle("D7HJQkH2Bb", "htmlElement")}
          >
            {
              <ImagePrimitive
                id={"Image_Cb9Dw6hbfB"}
                className={
                  "__visly_reset_7X7HTLRqyD __visly_scope_66HuVt3A5E_Cb9Dw6hbfB"
                }
                key={"Cb9Dw6hbfB"}
                src={
                  exists(props.imageSrc)
                    ? props.imageSrc
                    : getStyle("Cb9Dw6hbfB", "src")
                }
                alt={getStyle("Cb9Dw6hbfB", "alternateText")}
              />
            }
          </ContainerPrimitive>
          <TextPrimitive
            id={"Text_Rhtn315AoC"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_66HuVt3A5E_Rhtn315AoC"
            }
            key={"Rhtn315AoC"}
            text={getStyle("Rhtn315AoC", "text")}
            element={getStyle("Rhtn315AoC", "htmlElement")}
          />
        </>
      )}
    </RootPrimitive>
  );
}

Landing.__variants = [
  {
    name: "example",
    type: "variant",
  },
];

export default Landing;
