// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "../reset.css";
import "./Navbar.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../_internal_utils";
import {
  RootPrimitive,
  ImagePrimitive,
  ContainerPrimitive,
} from "../_internal_primitives";
import { default as SignIn } from "../Components/Navbar/SignIn";

const styles = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "example",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      YEDRjrbQq5: {},
    },
  },
  {
    type: "boolean",
    propName: "example",
    layers: {
      YEDRjrbQq5: {},
    },
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "example",
  },
];

export const NavbarContext = createContext(null);

function Navbar(_props) {
  const defaults = useContext(NavbarContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="LvxidMzP6M"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "LvxidMzP6M",
        scope: "49hJ88cQKh",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <ImagePrimitive
            id={"Logo_JBsUW8oRMy"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_49hJ88cQKh_JBsUW8oRMy"
            }
            key={"JBsUW8oRMy"}
            src={
              exists(props.imageSrc)
                ? props.imageSrc
                : getStyle("JBsUW8oRMy", "src")
            }
            alt={getStyle("JBsUW8oRMy", "alternateText")}
          />
          <ContainerPrimitive
            id={"NavLinks_8ruEmV82ch"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_49hJ88cQKh_8ruEmV82ch"
            }
            key={"8ruEmV82ch"}
            addSpacing={false}
            element={getStyle("8ruEmV82ch", "htmlElement")}
          >
            {null}
          </ContainerPrimitive>
          <ContainerPrimitive
            id={"Container_2MCpoSa1cQ"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_49hJ88cQKh_2MCpoSa1cQ"
            }
            key={"2MCpoSa1cQ"}
            addSpacing={false}
            element={getStyle("2MCpoSa1cQ", "htmlElement")}
          >
            {
              <ContainerPrimitive
                key={"4fTk9XDbJH"}
                id={"Slot_4fTk9XDbJH"}
                className={
                  "__visly_reset_7X7HTLRqyD __visly_scope_49hJ88cQKh_4fTk9XDbJH"
                }
                addSpacing={false}
              >
                {props.AccountButton}
              </ContainerPrimitive>
            }
          </ContainerPrimitive>
        </>
      )}
    </RootPrimitive>
  );
}

Navbar.SignIn = SignIn;
Navbar.__variants = [
  {
    name: "example",
    type: "variant",
  },
];

export default Navbar;
