// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import component_0 from "./SongDetail";
import component_1 from "./SongEntry";
import component_2 from "./SongList";
export const SongDetail = component_0;
export const SongEntry = component_1;
export const SongList = component_2;
