// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import component_0 from "./SongEntry";
import component_1 from "./SongList";
export const SongEntry = component_0;
export const SongList = component_1;
