// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../../textstyles/fonts.css";
import "../../reset.css";
import "./SongList.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../../_internal_utils";
import { RootPrimitive, ContainerPrimitive } from "../../_internal_primitives";
import {
  default as Example2,
  default as Example3,
  default as Example1,
} from "../../Components/Song/SongEntry";

const styles = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "example",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      LASPFQdSnN: {},
      "8689fgACCR": {},
      "75cjkht8UM": {},
    },
  },
  {
    type: "boolean",
    propName: "example",
    layers: {
      LASPFQdSnN: {
        none: {
          songName: "Laughing Dolphins",
        },
      },
      "8689fgACCR": {},
      "75cjkht8UM": {},
    },
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "example",
  },
];

export const SongListContext = createContext(null);

function SongList(_props) {
  const defaults = useContext(SongListContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="3NgVbc2DRn"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "3NgVbc2DRn",
        scope: "HCe4MVdiJL",
        activeVariants: activeVariants,
      }}
    >
      <ContainerPrimitive
        key={"21G8uFsPjt"}
        id={"Slot_21G8uFsPjt"}
        className={
          "__visly_reset_7X7HTLRqyD __visly_scope_HCe4MVdiJL_21G8uFsPjt"
        }
        addSpacing={false}
      >
        {props.children}
      </ContainerPrimitive>
    </RootPrimitive>
  );
}

SongList.Example2 = Example2;
SongList.Example3 = Example3;
SongList.Example1 = Example1;
SongList.__variants = [
  {
    name: "example",
    type: "variant",
  },
];

export default SongList;
