// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../../textstyles/fonts.css";
import "../../reset.css";
import "./SongEntry.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../../_internal_utils";
import {
  RootPrimitive,
  SpacerPrimitive,
  TextPrimitive,
  ContainerPrimitive,
} from "../../_internal_primitives";
import * as icons from "../../icons";
import { default as ProgressBar, ProgressBarContext } from "../../ProgressBar";
import { default as IconButton, IconButtonContext } from "../../IconButton";

const styles = [
  {
    type: "default",
    layers: {
      Q1HXmHodEF: {
        none: {
          text: "Autonomous Giraffes",
        },
      },
      UjEVxsyeQH: {
        none: {
          text: "Dec 25, 2020",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      JSMrfpTbbX: {
        none: {
          disabled: false,
          secondary: false,
        },
      },
      BL4cC8cLj1: {
        none: {
          icon: icons.arrowRight,
        },
      },
    },
  },
];

const variantPropTypes = [];

export const SongEntryContext = createContext(null);

function SongEntry(_props) {
  const defaults = useContext(SongEntryContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="RAHxuNWRgN"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "RAHxuNWRgN",
        scope: "HgquYGqsg9",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => [
        <TextPrimitive
          id={"Name_Q1HXmHodEF"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_HgquYGqsg9_Q1HXmHodEF"
          }
          key={"Q1HXmHodEF"}
          text={
            exists(props.songName)
              ? props.songName
              : getStyle("Q1HXmHodEF", "text")
          }
          element={getStyle("Q1HXmHodEF", "htmlElement")}
        />,
        <TextPrimitive
          id={"Date_UjEVxsyeQH"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_HgquYGqsg9_UjEVxsyeQH"
          }
          key={"UjEVxsyeQH"}
          text={
            exists(props.dateName)
              ? props.dateName
              : getStyle("UjEVxsyeQH", "text")
          }
          element={getStyle("UjEVxsyeQH", "htmlElement")}
        />,
        <ContainerPrimitive
          id={"Container_2snvFPnzJU"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_HgquYGqsg9_2snvFPnzJU"
          }
          key={"2snvFPnzJU"}
          addSpacing={false}
          element={getStyle("2snvFPnzJU", "htmlElement")}
        >
          {props.ProgressBar === undefined ? (
            <ProgressBar
              key={"JSMrfpTbbX"}
              {...getCompositeDefaultProps("JSMrfpTbbX")}
              id="ProgressBar_JSMrfpTbbX"
              className="__visly_reset_7X7HTLRqyD __visly_scope_HgquYGqsg9_JSMrfpTbbX"
            />
          ) : (
            <ProgressBarContext.Provider
              key="JSMrfpTbbX-provider"
              value={{
                key: "JSMrfpTbbX",
                id: "ProgressBar_JSMrfpTbbX",
                className:
                  "__visly_reset_7X7HTLRqyD __visly_scope_HgquYGqsg9_JSMrfpTbbX",
                ...getCompositeDefaultProps("JSMrfpTbbX"),
              }}
            >
              {props.ProgressBar}
            </ProgressBarContext.Provider>
          )}
        </ContainerPrimitive>,
        <SpacerPrimitive
          id={"Spacer_51JzEs6qEB"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_HgquYGqsg9_51JzEs6qEB"
          }
          key={"51JzEs6qEB"}
        />,
        props.IconButton === undefined ? (
          <IconButton
            key={"BL4cC8cLj1"}
            {...getCompositeDefaultProps("BL4cC8cLj1")}
            id="IconButton_BL4cC8cLj1"
            className="__visly_reset_7X7HTLRqyD __visly_scope_HgquYGqsg9_BL4cC8cLj1"
          />
        ) : (
          <IconButtonContext.Provider
            key="BL4cC8cLj1-provider"
            value={{
              key: "BL4cC8cLj1",
              id: "IconButton_BL4cC8cLj1",
              className:
                "__visly_reset_7X7HTLRqyD __visly_scope_HgquYGqsg9_BL4cC8cLj1",
              ...getCompositeDefaultProps("BL4cC8cLj1"),
            }}
          >
            {props.IconButton}
          </IconButtonContext.Provider>
        ),
      ]}
    </RootPrimitive>
  );
}

SongEntry.ProgressBar = ProgressBar;
SongEntry.IconButton = IconButton;
SongEntry.__variants = [];

export default SongEntry;
