// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../../textstyles/fonts.css";
import "../../reset.css";
import "./SongDetail.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../../_internal_utils";
import {
  RootPrimitive,
  TextPrimitive,
  ContainerPrimitive,
} from "../../_internal_primitives";
import * as icons from "../../icons";
import { default as IconButton, IconButtonContext } from "../../IconButton";

const styles = [
  {
    type: "default",
    layers: {
      "72mta6mxDz": {
        none: {
          text: "Unexpecting Octopus",
        },
      },
      GjP3Hgoa3y: {
        none: {
          text: "Beat 2",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      WMUNo4PYjD: {
        none: {
          icon: icons.arrowRight,
        },
      },
    },
  },
];

const variantPropTypes = [];

export const SongDetailContext = createContext(null);

function SongDetail(_props) {
  const defaults = useContext(SongDetailContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="iDar5waLsp"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "iDar5waLsp",
        scope: "YF2T27v7M2",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <TextPrimitive
            id={"Name_72mta6mxDz"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_YF2T27v7M2_72mta6mxDz"
            }
            key={"72mta6mxDz"}
            text={
              exists(props.name) ? props.name : getStyle("72mta6mxDz", "text")
            }
            element={getStyle("72mta6mxDz", "htmlElement")}
          />
          <TextPrimitive
            id={"Type_GjP3Hgoa3y"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_YF2T27v7M2_GjP3Hgoa3y"
            }
            key={"GjP3Hgoa3y"}
            text={
              exists(props.type) ? props.type : getStyle("GjP3Hgoa3y", "text")
            }
            element={getStyle("GjP3Hgoa3y", "htmlElement")}
          />
          <ContainerPrimitive
            id={"Container_GRYgYhc8dn"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_YF2T27v7M2_GRYgYhc8dn"
            }
            key={"GRYgYhc8dn"}
            addSpacing={false}
            element={getStyle("GRYgYhc8dn", "htmlElement")}
          >
            {props.IconButton === undefined ? (
              <IconButton
                key={"WMUNo4PYjD"}
                {...getCompositeDefaultProps("WMUNo4PYjD")}
                id="IconButton_WMUNo4PYjD"
                className="__visly_reset_7X7HTLRqyD __visly_scope_YF2T27v7M2_WMUNo4PYjD"
              />
            ) : (
              <IconButtonContext.Provider
                key="WMUNo4PYjD-provider"
                value={{
                  key: "WMUNo4PYjD",
                  id: "IconButton_WMUNo4PYjD",
                  className:
                    "__visly_reset_7X7HTLRqyD __visly_scope_YF2T27v7M2_WMUNo4PYjD",
                  ...getCompositeDefaultProps("WMUNo4PYjD"),
                }}
              >
                {props.IconButton}
              </IconButtonContext.Provider>
            )}
          </ContainerPrimitive>
        </>
      )}
    </RootPrimitive>
  );
}

SongDetail.IconButton = IconButton;
SongDetail.__variants = [];

export default SongDetail;
