// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import component_0 from "./BeatLabel";
import component_1 from "./TrackButton";
import component_2 from "./TrackColumn";
import component_3 from "./TrackColumn.ExampleColumn";
import component_4 from "./TrackLabel";
import component_5 from "./TrackTable";
import component_6 from "./TrackTable.ExampleNotes";
import component_7 from "./TrackTable.ExampleGrid";
import component_8 from "./TrackTable.ExampleMarkers";
export const BeatLabel = component_0;
export const TrackButton = component_1;
export const TrackColumn = component_2;
export const TrackLabel = component_4;
export const TrackTable = component_5;
TrackColumn.ExampleColumn = component_3;
TrackTable.ExampleNotes = component_6;
TrackTable.ExampleGrid = component_7;
TrackTable.ExampleMarkers = component_8;
