// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import component_0 from "./BeatLabel";
import component_1 from "./TrackButton";
import component_2 from "./TrackLabel";
import component_3 from "./TrackTable";
import component_4 from "./TrackTable.ExampleNotes";
import component_5 from "./TrackTable.ExampleGrid";
import component_6 from "./TrackTable.ExampleMarkers";
export const BeatLabel = component_0;
export const TrackButton = component_1;
export const TrackLabel = component_2;
export const TrackTable = component_3;
TrackTable.ExampleNotes = component_4;
TrackTable.ExampleGrid = component_5;
TrackTable.ExampleMarkers = component_6;
