// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../../../textstyles/fonts.css";
import "../../../reset.css";
import "./TrackTable.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../../../_internal_utils";
import {
  RootPrimitive,
  ContainerPrimitive,
} from "../../../_internal_primitives";
import {
  default as BeatLabel,
  BeatLabelContext,
} from "../../../Components/Editor/Track/BeatLabel";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      W2zUvdGDZr: {
        none: {
          text: " ",
        },
      },
    },
  },
];

const variantPropTypes = [];

export const TrackTableContext = createContext(null);

function TrackTable(_props) {
  const defaults = useContext(TrackTableContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="KMs5mMpQoH"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "KMs5mMpQoH",
        scope: "3gFi4GmK8Q",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <ContainerPrimitive
          id={"Container_HgCWTmknpr"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_3gFi4GmK8Q_HgCWTmknpr"
          }
          key={"HgCWTmknpr"}
          addSpacing={false}
          element={getStyle("HgCWTmknpr", "htmlElement")}
        >
          {
            <ContainerPrimitive
              id={"Container_2jYR5JgRKo"}
              className={
                "__visly_reset_7X7HTLRqyD __visly_scope_3gFi4GmK8Q_2jYR5JgRKo"
              }
              key={"2jYR5JgRKo"}
              addSpacing={false}
              element={getStyle("2jYR5JgRKo", "htmlElement")}
            >
              <ContainerPrimitive
                id={"Container_Uu8tbiUzS5"}
                className={
                  "__visly_reset_7X7HTLRqyD __visly_scope_3gFi4GmK8Q_Uu8tbiUzS5"
                }
                key={"Uu8tbiUzS5"}
                addSpacing={false}
                element={getStyle("Uu8tbiUzS5", "htmlElement")}
              >
                {[
                  props.BeatLabel === undefined ? (
                    <BeatLabel
                      key={"W2zUvdGDZr"}
                      {...getCompositeDefaultProps("W2zUvdGDZr")}
                      id="BeatLabel_W2zUvdGDZr"
                      className="__visly_reset_7X7HTLRqyD __visly_scope_3gFi4GmK8Q_W2zUvdGDZr"
                    />
                  ) : (
                    <BeatLabelContext.Provider
                      key="W2zUvdGDZr-provider"
                      value={{
                        key: "W2zUvdGDZr",
                        id: "BeatLabel_W2zUvdGDZr",
                        className:
                          "__visly_reset_7X7HTLRqyD __visly_scope_3gFi4GmK8Q_W2zUvdGDZr",
                        ...getCompositeDefaultProps("W2zUvdGDZr"),
                      }}
                    >
                      {props.BeatLabel}
                    </BeatLabelContext.Provider>
                  ),
                  <ContainerPrimitive
                    key={"KhFuwgXjAr"}
                    id={"Slot_KhFuwgXjAr"}
                    className={
                      "__visly_reset_7X7HTLRqyD __visly_scope_3gFi4GmK8Q_KhFuwgXjAr"
                    }
                    addSpacing={false}
                  >
                    {props.Notes}
                  </ContainerPrimitive>,
                ]}
              </ContainerPrimitive>
              <ContainerPrimitive
                id={"Container_LZDRzAGv4p"}
                className={
                  "__visly_reset_7X7HTLRqyD __visly_scope_3gFi4GmK8Q_LZDRzAGv4p"
                }
                key={"LZDRzAGv4p"}
                addSpacing={false}
                element={getStyle("LZDRzAGv4p", "htmlElement")}
              >
                <ContainerPrimitive
                  key={"7qgkNAeTiz"}
                  id={"Slot_7qgkNAeTiz"}
                  className={
                    "__visly_reset_7X7HTLRqyD __visly_scope_3gFi4GmK8Q_7qgkNAeTiz"
                  }
                  addSpacing={false}
                >
                  {props.Markers}
                </ContainerPrimitive>
                <ContainerPrimitive
                  key={"DxgerYMx4b"}
                  id={"Slot_DxgerYMx4b"}
                  className={
                    "__visly_reset_7X7HTLRqyD __visly_scope_3gFi4GmK8Q_DxgerYMx4b"
                  }
                  addSpacing={false}
                >
                  {props.Grid}
                </ContainerPrimitive>
              </ContainerPrimitive>
              <ContainerPrimitive
                id={"Container_CdHR4Fp5VU"}
                className={
                  "__visly_reset_7X7HTLRqyD __visly_scope_3gFi4GmK8Q_CdHR4Fp5VU"
                }
                key={"CdHR4Fp5VU"}
                addSpacing={false}
                element={getStyle("CdHR4Fp5VU", "htmlElement")}
              >
                {null}
              </ContainerPrimitive>
            </ContainerPrimitive>
          }
        </ContainerPrimitive>
      )}
    </RootPrimitive>
  );
}

TrackTable.BeatLabel = BeatLabel;
TrackTable.__variants = [];

export default TrackTable;
