// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../../../textstyles/fonts.css";
import "../../../reset.css";
import "./TrackColumn.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../../../_internal_utils";
import {
  RootPrimitive,
  ContainerPrimitive,
} from "../../../_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const TrackColumnContext = createContext(null);

function TrackColumn(_props) {
  const defaults = useContext(TrackColumnContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="13t22d3if7"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "13t22d3if7",
        scope: "CPsbqMfgTi",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <ContainerPrimitive
          id={"Container_QNDstsCwQD"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_CPsbqMfgTi_QNDstsCwQD"
          }
          key={"QNDstsCwQD"}
          addSpacing={false}
          element={getStyle("QNDstsCwQD", "htmlElement")}
        >
          {
            <ContainerPrimitive
              key={"gHqLQ4BdFm"}
              id={"Slot_gHqLQ4BdFm"}
              className={
                "__visly_reset_7X7HTLRqyD __visly_scope_CPsbqMfgTi_gHqLQ4BdFm"
              }
              addSpacing={false}
            >
              {props.children}
            </ContainerPrimitive>
          }
        </ContainerPrimitive>
      )}
    </RootPrimitive>
  );
}

TrackColumn.__variants = [];

export default TrackColumn;
