// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import {
  default as TrackButton,
  default as TrackButton1,
  default as TrackButton2,
  default as TrackButton3,
  default as TrackButton4,
  default as TrackButton5,
  default as TrackButton6,
  default as TrackButton7,
  default as TrackButton8,
  default as TrackButton9,
  default as TrackButton10,
  default as TrackButton11,
  default as TrackButton1011,
  default as TrackButton10111,
  default as TrackButton101111,
  default as TrackButton1011111,
  default as TrackButton10111111,
  default as TrackButton101111111,
  default as TrackButton1011111111,
  default as TrackButton10111111111,
  default as TrackButton101111111111,
  default as TrackButton1011111111111,
  default as TrackButton10111111111111,
  default as TrackButton101111111111111,
  default as TrackButton1011111111111111,
  default as TrackButton10111111111111111,
  default as TrackButton101111111111111111,
  default as TrackButton1011111111111111111,
  default as TrackButton10111111111111111111,
  default as TrackButton101111111111111111111,
  default as TrackButton1011111111111111111111,
  default as TrackButton10111111111111111111111,
  default as TrackButton101111111111111111111111,
  default as TrackButton1011111111111111111111111,
  default as TrackButton10111111111111111111111111,
  default as TrackButton101111111111111111111111111,
  default as TrackButton1011111111111111111111111111,
  default as TrackButton10111111111111111111111111111,
  default as TrackButton101111111111111111111111111111,
  default as TrackButton1011111111111111111111111111111,
  default as TrackButton10111111111111111111111111111111,
  default as TrackButton101111111111111111111111111111111,
  default as TrackButton1011111111111111111111111111111111,
  default as TrackButton10111111111111111111111111111111111,
  default as TrackButton101111111111111111111111111111111111,
  default as TrackButton1011111111111111111111111111111111111,
  default as TrackButton10111111111111111111111111111111111111,
  default as TrackButton101111111111111111111111111111111111111,
  default as TrackButton1011111111111111111111111111111111111111,
  default as TrackButton10111111111111111111111111111111111111111,
  default as TrackButton101111111111111111111111111111111111111111,
  default as TrackButton1011111111111111111111111111111111111111111,
  default as TrackButton10111111111111111111111111111111111111111111,
  default as TrackButton101111111111111111111111111111111111111111111,
  default as TrackButton1011111111111111111111111111111111111111111111,
  default as TrackButton10111111111111111111111111111111111111111111111,
  default as TrackButton101111111111111111111111111111111111111111111111,
  default as TrackButton1011111111111111111111111111111111111111111111111,
  default as TrackButton10111111111111111111111111111111111111111111111111,
  default as TrackButton101111111111111111111111111111111111111111111111111,
  default as TrackButton1011111111111111111111111111111111111111111111111111,
  default as TrackButton10111111111111111111111111111111111111111111111111111,
  default as TrackButton101111111111111111111111111111111111111111111111111111,
  default as TrackButton1011111111111111111111111111111111111111111111111111111,
} from "./Components/Editor/Track/TrackButton";
import React from "react";
export interface CommonProps<T extends HTMLElement> {
  className?: string;
  style?: React.CSSProperties;
  innerRef?: React.MutableElementRef<T> | React.RefCallback<T>;
  tabIndex?: number;
  role?: string;
  testId?: string;
  disabled?: boolean;
  onAuxClick?: React.MouseEventHandler<T>;
  onAuxClickCapture?: React.MouseEventHandler<T>;
  onClick?: React.MouseEventHandler<T>;
  onClickCapture?: React.MouseEventHandler<T>;
  onContextMenu?: React.MouseEventHandler<T>;
  onContextMenuCapture?: React.MouseEventHandler<T>;
  onDoubleClick?: React.MouseEventHandler<T>;
  onDoubleClickCapture?: React.MouseEventHandler<T>;
  onDrag?: React.DragEventHandler<T>;
  onDragCapture?: React.DragEventHandler<T>;
  onDragEnd?: React.DragEventHandler<T>;
  onDragEndCapture?: React.DragEventHandler<T>;
  onDragEnter?: React.DragEventHandler<T>;
  onDragEnterCapture?: React.DragEventHandler<T>;
  onDragExit?: React.DragEventHandler<T>;
  onDragExitCapture?: React.DragEventHandler<T>;
  onDragLeave?: React.DragEventHandler<T>;
  onDragLeaveCapture?: React.DragEventHandler<T>;
  onDragOver?: React.DragEventHandler<T>;
  onDragOverCapture?: React.DragEventHandler<T>;
  onDragStart?: React.DragEventHandler<T>;
  onDragStartCapture?: React.DragEventHandler<T>;
  onDrop?: React.DragEventHandler<T>;
  onDropCapture?: React.DragEventHandler<T>;
  onMouseDown?: React.MouseEventHandler<T>;
  onMouseDownCapture?: React.MouseEventHandler<T>;
  onMouseEnter?: React.MouseEventHandler<T>;
  onMouseLeave?: React.MouseEventHandler<T>;
  onMouseMove?: React.MouseEventHandler<T>;
  onMouseMoveCapture?: React.MouseEventHandler<T>;
  onMouseOut?: React.MouseEventHandler<T>;
  onMouseOutCapture?: React.MouseEventHandler<T>;
  onMouseOver?: React.MouseEventHandler<T>;
  onMouseOverCapture?: React.MouseEventHandler<T>;
  onMouseUp?: React.MouseEventHandler<T>;
  onMouseUpCapture?: React.MouseEventHandler<T>;
  onTouchCancel?: React.TouchEventHandler<T>;
  onTouchCancelCapture?: React.TouchEventHandler<T>;
  onTouchEnd?: React.TouchEventHandler<T>;
  onTouchEndCapture?: React.TouchEventHandler<T>;
  onTouchMove?: React.TouchEventHandler<T>;
  onTouchMoveCapture?: React.TouchEventHandler<T>;
  onTouchStart?: React.TouchEventHandler<T>;
  onTouchStartCapture?: React.TouchEventHandler<T>;
  onPointerDown?: React.PointerEventHandler<T>;
  onPointerDownCapture?: React.PointerEventHandler<T>;
  onPointerMove?: React.PointerEventHandler<T>;
  onPointerMoveCapture?: React.PointerEventHandler<T>;
  onPointerUp?: React.PointerEventHandler<T>;
  onPointerUpCapture?: React.PointerEventHandler<T>;
  onPointerCancel?: React.PointerEventHandler<T>;
  onPointerCancelCapture?: React.PointerEventHandler<T>;
  onPointerEnter?: React.PointerEventHandler<T>;
  onPointerLeave?: React.PointerEventHandler<T>;
  onPointerOver?: React.PointerEventHandler<T>;
  onPointerOverCapture?: React.PointerEventHandler<T>;
  onPointerOut?: React.PointerEventHandler<T>;
  onPointerOutCapture?: React.PointerEventHandler<T>;
  onGotPointerCapture?: React.PointerEventHandler<T>;
  onGotPointerCaptureCapture?: React.PointerEventHandler<T>;
  onLostPointerCapture?: React.PointerEventHandler<T>;
  onLostPointerCaptureCapture?: React.PointerEventHandler<T>;
  onScroll?: React.UIEventHandler<T>;
  onScrollCapture?: React.UIEventHandler<T>;
  onWheel?: React.WheelEventHandler<T>;
  onWheelCapture?: React.WheelEventHandler<T>;
  onKeyDown?: React.KeyboardEventHandler<T>;
  onKeyDownCapture?: React.KeyboardEventHandler<T>;
  onKeyPress?: React.KeyboardEventHandler<T>;
  onKeyPressCapture?: React.KeyboardEventHandler<T>;
  onKeyUp?: React.KeyboardEventHandler<T>;
  onKeyUpCapture?: React.KeyboardEventHandler<T>;
  onFocus?: React.FocusEventHandler<T>;
  onFocusCapture?: React.FocusEventHandler<T>;
  onBlur?: React.FocusEventHandler<T>;
  onBlurCapture?: React.FocusEventHandler<T>;
}
const ExampleGrid: {
  (
    props: {
      TrackButton?: React.ReactNode;
      TrackButton1?: React.ReactNode;
      TrackButton2?: React.ReactNode;
      TrackButton3?: React.ReactNode;
      TrackButton4?: React.ReactNode;
      TrackButton5?: React.ReactNode;
      TrackButton6?: React.ReactNode;
      TrackButton7?: React.ReactNode;
      TrackButton8?: React.ReactNode;
      TrackButton9?: React.ReactNode;
      TrackButton10?: React.ReactNode;
      TrackButton11?: React.ReactNode;
      TrackButton1011?: React.ReactNode;
      TrackButton10111?: React.ReactNode;
      TrackButton101111?: React.ReactNode;
      TrackButton1011111?: React.ReactNode;
      TrackButton10111111?: React.ReactNode;
      TrackButton101111111?: React.ReactNode;
      TrackButton1011111111?: React.ReactNode;
      TrackButton10111111111?: React.ReactNode;
      TrackButton101111111111?: React.ReactNode;
      TrackButton1011111111111?: React.ReactNode;
      TrackButton10111111111111?: React.ReactNode;
      TrackButton101111111111111?: React.ReactNode;
      TrackButton1011111111111111?: React.ReactNode;
      TrackButton10111111111111111?: React.ReactNode;
      TrackButton101111111111111111?: React.ReactNode;
      TrackButton1011111111111111111?: React.ReactNode;
      TrackButton10111111111111111111?: React.ReactNode;
      TrackButton101111111111111111111?: React.ReactNode;
      TrackButton1011111111111111111111?: React.ReactNode;
      TrackButton10111111111111111111111?: React.ReactNode;
      TrackButton101111111111111111111111?: React.ReactNode;
      TrackButton1011111111111111111111111?: React.ReactNode;
      TrackButton10111111111111111111111111?: React.ReactNode;
      TrackButton101111111111111111111111111?: React.ReactNode;
      TrackButton1011111111111111111111111111?: React.ReactNode;
      TrackButton10111111111111111111111111111?: React.ReactNode;
      TrackButton101111111111111111111111111111?: React.ReactNode;
      TrackButton1011111111111111111111111111111?: React.ReactNode;
      TrackButton10111111111111111111111111111111?: React.ReactNode;
      TrackButton101111111111111111111111111111111?: React.ReactNode;
      TrackButton1011111111111111111111111111111111?: React.ReactNode;
      TrackButton10111111111111111111111111111111111?: React.ReactNode;
      TrackButton101111111111111111111111111111111111?: React.ReactNode;
      TrackButton1011111111111111111111111111111111111?: React.ReactNode;
      TrackButton10111111111111111111111111111111111111?: React.ReactNode;
      TrackButton101111111111111111111111111111111111111?: React.ReactNode;
      TrackButton1011111111111111111111111111111111111111?: React.ReactNode;
      TrackButton10111111111111111111111111111111111111111?: React.ReactNode;
      TrackButton101111111111111111111111111111111111111111?: React.ReactNode;
      TrackButton1011111111111111111111111111111111111111111?: React.ReactNode;
      TrackButton10111111111111111111111111111111111111111111?: React.ReactNode;
      TrackButton101111111111111111111111111111111111111111111?: React.ReactNode;
      TrackButton1011111111111111111111111111111111111111111111?: React.ReactNode;
      TrackButton10111111111111111111111111111111111111111111111?: React.ReactNode;
      TrackButton101111111111111111111111111111111111111111111111?: React.ReactNode;
      TrackButton1011111111111111111111111111111111111111111111111?: React.ReactNode;
      TrackButton10111111111111111111111111111111111111111111111111?: React.ReactNode;
      TrackButton101111111111111111111111111111111111111111111111111?: React.ReactNode;
      TrackButton1011111111111111111111111111111111111111111111111111?: React.ReactNode;
      TrackButton10111111111111111111111111111111111111111111111111111?: React.ReactNode;
      TrackButton101111111111111111111111111111111111111111111111111111?: React.ReactNode;
      TrackButton1011111111111111111111111111111111111111111111111111111?: React.ReactNode;
    } & CommonProps<HTMLDivElement>
  ): JSX.Element;
  TrackButton: typeof TrackButton;
  TrackButton1: typeof TrackButton1;
  TrackButton2: typeof TrackButton2;
  TrackButton3: typeof TrackButton3;
  TrackButton4: typeof TrackButton4;
  TrackButton5: typeof TrackButton5;
  TrackButton6: typeof TrackButton6;
  TrackButton7: typeof TrackButton7;
  TrackButton8: typeof TrackButton8;
  TrackButton9: typeof TrackButton9;
  TrackButton10: typeof TrackButton10;
  TrackButton11: typeof TrackButton11;
  TrackButton1011: typeof TrackButton1011;
  TrackButton10111: typeof TrackButton10111;
  TrackButton101111: typeof TrackButton101111;
  TrackButton1011111: typeof TrackButton1011111;
  TrackButton10111111: typeof TrackButton10111111;
  TrackButton101111111: typeof TrackButton101111111;
  TrackButton1011111111: typeof TrackButton1011111111;
  TrackButton10111111111: typeof TrackButton10111111111;
  TrackButton101111111111: typeof TrackButton101111111111;
  TrackButton1011111111111: typeof TrackButton1011111111111;
  TrackButton10111111111111: typeof TrackButton10111111111111;
  TrackButton101111111111111: typeof TrackButton101111111111111;
  TrackButton1011111111111111: typeof TrackButton1011111111111111;
  TrackButton10111111111111111: typeof TrackButton10111111111111111;
  TrackButton101111111111111111: typeof TrackButton101111111111111111;
  TrackButton1011111111111111111: typeof TrackButton1011111111111111111;
  TrackButton10111111111111111111: typeof TrackButton10111111111111111111;
  TrackButton101111111111111111111: typeof TrackButton101111111111111111111;
  TrackButton1011111111111111111111: typeof TrackButton1011111111111111111111;
  TrackButton10111111111111111111111: typeof TrackButton10111111111111111111111;
  TrackButton101111111111111111111111: typeof TrackButton101111111111111111111111;
  TrackButton1011111111111111111111111: typeof TrackButton1011111111111111111111111;
  TrackButton10111111111111111111111111: typeof TrackButton10111111111111111111111111;
  TrackButton101111111111111111111111111: typeof TrackButton101111111111111111111111111;
  TrackButton1011111111111111111111111111: typeof TrackButton1011111111111111111111111111;
  TrackButton10111111111111111111111111111: typeof TrackButton10111111111111111111111111111;
  TrackButton101111111111111111111111111111: typeof TrackButton101111111111111111111111111111;
  TrackButton1011111111111111111111111111111: typeof TrackButton1011111111111111111111111111111;
  TrackButton10111111111111111111111111111111: typeof TrackButton10111111111111111111111111111111;
  TrackButton101111111111111111111111111111111: typeof TrackButton101111111111111111111111111111111;
  TrackButton1011111111111111111111111111111111: typeof TrackButton1011111111111111111111111111111111;
  TrackButton10111111111111111111111111111111111: typeof TrackButton10111111111111111111111111111111111;
  TrackButton101111111111111111111111111111111111: typeof TrackButton101111111111111111111111111111111111;
  TrackButton1011111111111111111111111111111111111: typeof TrackButton1011111111111111111111111111111111111;
  TrackButton10111111111111111111111111111111111111: typeof TrackButton10111111111111111111111111111111111111;
  TrackButton101111111111111111111111111111111111111: typeof TrackButton101111111111111111111111111111111111111;
  TrackButton1011111111111111111111111111111111111111: typeof TrackButton1011111111111111111111111111111111111111;
  TrackButton10111111111111111111111111111111111111111: typeof TrackButton10111111111111111111111111111111111111111;
  TrackButton101111111111111111111111111111111111111111: typeof TrackButton101111111111111111111111111111111111111111;
  TrackButton1011111111111111111111111111111111111111111: typeof TrackButton1011111111111111111111111111111111111111111;
  TrackButton10111111111111111111111111111111111111111111: typeof TrackButton10111111111111111111111111111111111111111111;
  TrackButton101111111111111111111111111111111111111111111: typeof TrackButton101111111111111111111111111111111111111111111;
  TrackButton1011111111111111111111111111111111111111111111: typeof TrackButton1011111111111111111111111111111111111111111111;
  TrackButton10111111111111111111111111111111111111111111111: typeof TrackButton10111111111111111111111111111111111111111111111;
  TrackButton101111111111111111111111111111111111111111111111: typeof TrackButton101111111111111111111111111111111111111111111111;
  TrackButton1011111111111111111111111111111111111111111111111: typeof TrackButton1011111111111111111111111111111111111111111111111;
  TrackButton10111111111111111111111111111111111111111111111111: typeof TrackButton10111111111111111111111111111111111111111111111111;
  TrackButton101111111111111111111111111111111111111111111111111: typeof TrackButton101111111111111111111111111111111111111111111111111;
  TrackButton1011111111111111111111111111111111111111111111111111: typeof TrackButton1011111111111111111111111111111111111111111111111111;
  TrackButton10111111111111111111111111111111111111111111111111111: typeof TrackButton10111111111111111111111111111111111111111111111111111;
  TrackButton101111111111111111111111111111111111111111111111111111: typeof TrackButton101111111111111111111111111111111111111111111111111111;
  TrackButton1011111111111111111111111111111111111111111111111111111: typeof TrackButton1011111111111111111111111111111111111111111111111111111;
};
export default ExampleGrid;
